### ISSUE TITLE
Data integrity issues - running list

### ISSUE THREAD

**Issue by jkoul** [codefordc/dc-campaign-finance-watch#118]
Consider this an evolving list of particular issues with the API data. I'll create a separate issue for front-end rendering issues if any pop up.

- Charles Allen's page lists candidate-source contributions from 3 different wards. That's literally impossible (he lives at 16th & D NE, I've been to his house), so either something's wrong with the data or the heat map.

- The ward concentration scores seem lower than I was expecting.....I wonder if there's something off with the calculation. TBD......I'll try to verify in other ways.

- Some candidate contributions are misclassified as individual. I think we could say if they're from the candidate's address and name, recode the source as candidate?

**Comment by mkalish** [comment]
@jkoul Is this list mostly closed... I was going to add individual tickets for each issue

**Comment by jkoul** [comment]
Yeah, better as individual issues.

Also I'll check with folks about a hangout tomorrow. The one holdup is that
the guy who'd be most helpful to us is 100% incapable of figuring out
Google hangouts (he still uses compuserve for e-mail, which should say
enough). I'll talk to him and see if we can meet and join a hangout
together. Stay tuned...

On Sunday, April 10, 2016, mkalish <notifications@github.com> wrote:

> @jkoul <https://github.com/jkoul> Is this list mostly closed... I was
> going to add individual tickets for each issue
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/codefordc/dc-campaign-finance-watch/issues/118#issuecomment-208043624>
>


-- 
Jeremy Koulish
jkoulish@gmail.com
917-597-4397
http://kouli.sh

*We are drowning in information, while starving for wisdom. The world
henceforth will be run by synthesizers, people able to put together the
right information at the right time, think critically about it, and make
important choices wisely.*
*-E.O. Wilson*

**Comment by mkalish** [comment]
Opened tickets:
#140 
#141 
#142
