### ISSUE TITLE
Update database with up to date contributions

### ISSUE THREAD

**Issue by mkalish** [codefordc/dc-campaign-finance-watch#121]
Currently, there are contributions through 2014, but we should update this to capture data from the current cycle.

Steps:
- [ ]  Download csv from OCF (make sure the dates are correct so we don't double count contributions)
- [ ]  Run the csv through the address updater
- [ ]  Run the csv through the deduper (I have the training file)
- [ ]  Run the importer2 against the csv
- [ ]  Run the upgrade scripts

**Comment by bcell** [comment]
Which type of contributions are we compiling (as per "filter type" on https://efiling.ocf.dc.gov/ContributionExpenditure )? Principle Campaign Committee? Exploratory Committee? More?

**Comment by bcell** [comment]
In the previous file (DC_contribs_since_2007.csv) I am seeing:
Campaign Committee
PAC
Initiative
Referendum
Recall
Inaugural Committee
SuperPAC
Exploratory Committee
Statehood Delegation
Constituent Service Fund

**Comment by jkoul** [comment]
Guys.......the contribution data is from January 1 2007 - June 2015, which includes last year's Ward 4 and Ward 8 special elections.

I'm updating the about page accordingly and will submit a PR soon.

**Comment by jkoul** [comment]
And the data includes all types.......but if I'm not mistaken only campaign committees are currently included in the db models?

**Comment by mkalish** [comment]
All the data has is in the database, but everything not specifically related to a campaign was shoved into the "unprocessed contributions" collection, so it should be easy to go back and do something with them.

I'm thinking we should do the same thing here, pull down the all the data import it, but only the campaign data will actually become queryable to end users.

**Comment by mkalish** [comment]
Race Id Breakdown
{Digit, Digit} {Letter}
{Last Two Digits of year the campaign was run} {Unique ID for the race type}

Campaign ID Breakdown
{Digit, Digit}{Letter}{Digit}
{Last Two Digits of year the campaign was run} {Unique ID for the race type} {Unique ID for the candidate in the race}

**Comment by bcell** [comment]
[List of committees in recent data.xlsx](https://github.com/codefordc/dc-campaign-finance-watch/files/246877/List.of.committees.in.recent.data.xlsx)

Here is a table to the committees I am trying to match to candidates/races/campaigns. Please review, especially the highlighted ones.

**Comment by jkoul** [comment]
I'll review all of these today. I can def fill in the gaps.

On Tuesday, May 3, 2016, bcell <notifications@github.com> wrote:

> List of committees in recent data.xlsx
> <https://github.com/codefordc/dc-campaign-finance-watch/files/246877/List.of.committees.in.recent.data.xlsx>
>
> Here is a table to the committees I am trying to match to
> candidates/races/campaigns. Please review, especially the highlighted ones.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/codefordc/dc-campaign-finance-watch/issues/121#issuecomment-216517698>
>


-- 
Jeremy Koulish
jkoulish@gmail.com
917-597-4397
http://kouli.sh

*We are drowning in information, while starving for wisdom. The world
henceforth will be run by synthesizers, people able to put together the
right information at the right time, think critically about it, and make
important choices wisely.*
*-E.O. Wilson*

**Comment by bcell** [comment]
Any movement on this @jkoul?

**Comment by bcell** [comment]
The main thing I am missing is races. I want to be sure that the right people are grouped together.
Also, why committees apparently from years prior to 2015 receiving donations? Ex: Karl Racine For AG of campaign # 14B2. These are donations since 5/7/15.

**Comment by jkoul** [comment]
brent......can you gchat me and go through names with me? It might actually
be easier that way. jkoulish@gmail.com

On Thu, Jun 9, 2016 at 8:35 PM, bcell <notifications@github.com> wrote:

> The main thing I am missing is races. I want to be sure that the right
> people are grouped together.
> Also, why committees apparently from years prior to 2015 receiving
> donations? Ex: Karl Racine For AG of campaign # 14B2. These are donations
> since 5/7/15.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/codefordc/dc-campaign-finance-watch/issues/121#issuecomment-225065874>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMMAl45TuZjiSv1bil71K_quMkahKU1Pks5qKLFogaJpZM4H7q38>
> .
>



-- 
Jeremy Koulish
jkoulish@gmail.com
917-597-4397
http://kouli.sh

*We are drowning in information, while starving for wisdom. The world
henceforth will be run by synthesizers, people able to put together the
right information at the right time, think critically about it, and make
important choices wisely.*
*-E.O. Wilson*

**Comment by jkoul** [comment]
Actually I'm on slack.......how much have you updated in the spreadsheet. it might be easier to talk through with you

**Comment by bcell** [comment]
I updated this lookup file with highlights on all the unknown or uncertain info about the campaign committees.
[List.of.committees.in.recent.data.xlsx](https://github.com/codefordc/dc-campaign-finance-watch/files/372680/List.of.committees.in.recent.data.xlsx)
