### ISSUE TITLE
Add a new route focused on just the graphs

### ISSUE THREAD

**Issue by mkalish** [codefordc/dc-campaign-finance-watch#122]
As it stands, the looking at graphs between multiple candidates is not super intuitive.  I would like to add a new route that takes in a set of campaign ids and then renders the charts full screen in a manner that allows them to be combined as much as possible.  I.E for the "contributions over time" multiple campaigns can be plotted at the same time

- Bonus: ability to download the graphs as a PNG

**Comment by matthewringer** [comment]
I'll give this one a shot.
