### ISSUE TITLE
Add interface to see individual contributions for each campaign

### ISSUE THREAD

**Issue by jkoul** [codefordc/dc-campaign-finance-watch#130]
A big missing piece that I'd love to see addressed in the next version is a child view for each campaign that allows users to dig deeper into the contributions and parse them individually. This is doable even before we get the contributor model fully sorted out, and I believe it's significantly more important.

I've talked to multiple potential users who've recently used the current OCF portal to do just that, and I can say from personal experience that it's a pain. We have all the back-end pieces in place already, it's just about building a new page template, and that's mostly front-end work.

What do you all think? I can take ownership over this one and build/style the view if you're willing to help some with the controller (I'm just not too familiar with React).

**Comment by mkalish** [comment]
Yea, I'm thinking that we need more a larger milestone for this idea, but I think this is going to be a really important first step for this.  I'm planning to add several more issues related to this idea tomorrow; I'll let you know so you can review and comment.  If you wanted to throw together a really basic mockup of what you're thinking it should not take me too long to pull it all together.  I'm also happy to talk through some more of the technical stuff/ come up with the technical tasks that need to be done if you wanted to get more into the actual code.
