### ISSUE TITLE
Number Formatting

### ISSUE THREAD

**Issue by donaldbraman** [codefordc/dc-campaign-finance-watch#144]
Use simple number formatting

## Context
When presenting numbers in cards, numbers greater than zero should typically be rounded to zero decimal places.  Commas should be added for numbers greater than 999. 

## Expected Behavior
Dollar amounts should be rounded to whole dollars, with commas for each three places. E.g.: $123,456 rather than $123456.1234.  Percentages should be rounded to whole percentages.  More precision reduces readability and comprehension.

**Comment by mkalish** [comment]
Fixed by #145
