### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by mkalish** [codefordc/dc-campaign-finance-watch#148]
## Context
Adding a favicon adds a bit of a professional air to the site

## Expected Behavior
A favicon should appear in the tab

## Actual Behavior
There is no favicon

## Possible Fix
Add a favicon to the repo

**Comment by romoy** [comment]
https://github.com/codefordc/dc-campaign-finance-watch/pull/155/files

**Comment by romoy** [comment]
This is done.
