### ISSUE TITLE
Data output needs link to campaign score explanation

### ISSUE THREAD

**Issue by Elieri** [codefordc/dc-campaign-finance-watch#150]
Under the combined score figure for each campaign, the text "See here for explanation" does not contain a link
![campaign-score](https://cloud.githubusercontent.com/assets/6662612/14972384/4bd9eecc-10a9-11e6-9206-ae37fd945af3.jpg)

**Comment by mkalish** [comment]
#131 linking to that issue since the README fix will be temporary until we have an actual page

**Comment by romoy** [comment]
Seems fixed in the latest develop branch
<img width="584" alt="screen shot 2016-05-08 at 11 03 09 am" src="https://cloud.githubusercontent.com/assets/7241408/15098466/b68a3490-150c-11e6-9777-474da74c9edc.png">

**Comment by mkalish** [comment]
Yep, this has been fixed, but not pushed to the live site yet.  I'll close it when its been verified.
