### ISSUE TITLE
Add filter and sort controls for the campaign contributions

### ISSUE THREAD

**Issue by mkalish** [codefordc/dc-campaign-finance-watch#159]
As a user, I would like the ability to filter and sort the contributions by a variety of criteria including:
- contributor name (sort and filter)
- contribution amount (sort)
- contributor address (filter)
- contribution date (sort)
- contribution type (sort and filter)
- contribution ward (filter)
- contribution zip (filter)
- inside/outside DC (filter)

## Expected Behavior
I should have controls that allow the sorts/filters.  I also should have controls for resetting the sorts and filters

## Possible Fix
- [ ] research if there is a react table component to handle this already
- [ ] research what if any filter code needs to be run in the backend
- [ ] add the controls to the contribution breakdown component

**Comment by jamesfe** [comment]
Looking into this now - but I am having some trouble running the server.  I think I recall from our conversation that gulp is no longer used to run the server?  I'm getting a 'no gulpfile found' error when I run `gulp serve --env=prod`.

**Comment by mkalish** [comment]
Yea... we've added a new way of running the code.   You can do `npm run-scripts dev` now.

**Comment by mkalish** [comment]
Resolved by #172
