### ISSUE TITLE
As a user, I'd like each candidate's campaign score to appear next to her name on the home screen

### ISSUE THREAD

**Issue by kfrosty** [codefordc/dc-campaign-finance-watch#169]
Enhancement: Looking at the home page, it would be helpful to have some high-level information on each candidate. I recommend we start with the combined campaign score. For past campaigns, it would also be great to include what percentage of the vote each candidate received, or (if that's too messy), just an indication of who won the race.

**Comment by donaldbraman** [comment]
I agree!  Would also be nice to have that be the sort order.  Or give some indication -- green yellow red or some such -- of relative scores.

**Comment by mkalish** [comment]
Closed by #173
