### ISSUE TITLE
Quick fixes - FAQ page

### ISSUE THREAD

**Issue by kfrosty** [codefordc/dc-campaign-finance-watch#170]
A few typos and other easy fixes on the FAQ page: 
1. Add means of contact (e.g., email) to the answer to "What can you do if the data seems wrong?" It says to contact us, but it's not clear how. 
2. Clarify explanation of the scoring indicators. It currently says the score encompasses four categories, but then it lists then each twice, so it looks like eight. I recommend we update the language to: 

The score combines indicators encompassing three categories: 
- Location (40 points)
- Amount (30 points)
- Contributor Type (30 points)

In the future we may add a fourth category focused on Reporting.

**Comment by sdotson** [comment]
I took a crack at this in pull request 240.

**Comment by sdotson** [comment]
I think this issue can be closed now.

**Comment by mkalish** [comment]
Yep totally blanked on closing it! thanks
