### ISSUE TITLE
Contribution table shows the exploration view, and vice versa

### ISSUE THREAD

**Issue by adilyalcin** [codefordc/dc-campaign-finance-watch#190]
Title says it all:)

http://codefordc.org/dc-campaign-finance-watch/dist/candidate/56d5a1361441afc4104247bc/campaign/14D5

**Comment by romoy** [comment]
@adilyalcin This feature request lost a bit of context. 
What's the exploration view?
What's the desired steps a user would take to experience this feature?

**Comment by adilyalcin** [comment]
Hi @romoy, I'm closing the issue. It was a very early bug, and it's not relevant anymore. The title was a little cryptic. Basically, the tabs showed different content. A showed B, B showed A. Thanks!
