### ISSUE TITLE
The zipped db is no longer valid

### ISSUE THREAD

**Issue by romoy** [codefordc/dc-campaign-finance-watch#198]
After several massage and migration of the db information, the current zip is too old. 

## Expected Behavior

Candidate appear in the local web ui without migrating the data to fit the form expected by the api.

## Actual Behavior

The candidate data doesn't appear in web ui during local development.

## Possible Fix

Update the .zip snapshot and remove migration scripts.

## Steps to Reproduce

1. If you attempt to use the current data as is, the data will not appear in the web ui because the api is checking for a format which doesn't exist.

**Comment by romoy** [comment]
Discovered while working on https://github.com/codefordc/dc-campaign-finance-watch/pull/197

**Comment by mkalish** [comment]
New zip (dc-campaign-finance.zip) in the repo with the updated data.
