### ISSUE TITLE
What's needed to add pretty open source badges to this codebase?

### ISSUE THREAD

**Issue by romoy** [codefordc/dc-campaign-finance-watch#203]
Which open source badges could we add to signal that the code base is friendly?

## Context

I noticed that there was travis ci badge but it wasn't green.

## Expected Behavior

On first glance of the code base, a certain set of badges should reveal the overall health of the project.

## Actual Behavior

The health of the codebase is unclear.

## Possible Fix

Spike on possible solutions and create follow-up issues to implement the necessary changes.

**Comment by sdotson** [comment]
It looks like maybe it's because there haven't been any changes to the codebase in a while. https://travis-ci.org/codefordc/dc-campaign-finance-watch/

**Comment by romoy** [comment]
Updated my fork to https://travis-ci.org/romoy/dc-campaign-finance-watch to build and that's merged.
