### ISSUE TITLE
Front End changes not reflected in localhost

### ISSUE THREAD

**Issue by sdotson** [codefordc/dc-campaign-finance-watch#208]
## Context
Hello, I'm trying to work on some front end issues.

## Expected Behavior
When I make a change to a React component, I should see those changes reflected in my local environment either through a hot reload or by manually refreshing the page.

## Actual Behavior
Nothing changes

## Possible Fix
Perhaps there's some sort of cache that needs to be cleared whenever we run the dockerfile?

## Steps to Reproduce
1. `docker-compose up dc-campaign-finance-ui`
2. Make a change to any React component or insert a console.log somewhere
3. Refresh page and stare in disbelief as nothing as changed
4. Rinse, lather, repeat

## Context
I was trying to tackle a reported front end issue in this repo.

## Your Environment
* Mac El Capitan
* Chrome

**Comment by romoy** [comment]
I added a workaround in #209 . I'm troubleshooting the docker config.

**Comment by sdotson** [comment]
Hey thanks @romoy , I'll take a look.

**Comment by mkalish** [comment]
Closed mostly by #209
