### ISSUE TITLE
Keshif Browser is not loading due to mixed-content error

### ISSUE THREAD

**Issue by romoy** [codefordc/dc-campaign-finance-watch#210]
Keshif Browser is not loading due to mixed content error. Attempting to access http while on https domain.

## Expected Behavior

1. Keshif browser load candidate details.

## Actual Behavior

1. Keshif iframe is blank.
2. The following error in console.
`DOMLazyTree.js:69 Mixed Content: The page at 'https://codefordc.org/dc-campaign-finance-watch/dist/candidate/56d5a1361441afc4104247bc/campaign/14D5' was loaded over HTTPS, but requested an insecure resource 'http://adilyalcin.me/campaign-finance-explorer/index.html?14D5'. This request has been blocked; the content must be served over HTTPS.
`

## Possible Fix

1. Add the appropriate certs to server hosting Keshif Browser

## Steps to Reproduce

1.Visit https://codefordc.org/dc-campaign-finance-watch/dist/
2. Click on a candidate
3. Click Details button for the candidate

## Your Environment

* Mac
* Chrome
* Desktop

**Comment by adilyalcin** [comment]
Hi @romoy ,

adilyalcin.me domain does not support https, and I'm not planning to change that soon.

You can move over the source code from https://github.com/adilyalcin/campaign-finance-explorer to the project, say under keshif directory, with all the files and licenses. Then, you can update the iframe embed code to point to new directory.

Let me know if you need any specific help.

**Comment by romoy** [comment]
Will attempt to deploy https://github.com/codefordc/campaign-finance-explorer as a service on the codefordc https domain then replaces calls to adilyalcin.me.

**Comment by romoy** [comment]
![screen shot 2017-05-02 at 07 23 02](https://cloud.githubusercontent.com/assets/7241408/25615995/4c2fb392-2f08-11e7-9a90-359d51e628e4.png)

This is fixed by updating Keshif url in dc-campaign-finance and updating the api reference in campaign-explorer.
