### ISSUE TITLE
Develop Branch does not build

### ISSUE THREAD

**Issue by tingaloo** [codefordc/dc-campaign-finance-watch#221]
## Context
Current develop branch does not build. Webpack fails to serve proper assets.  I traced the error back to commit [merged in develop and rebuild dist](https://github.com/codefordc/dc-campaign-finance-watch/commit/4b6ee0344a688b24270137566baf1f5dce647719)

## Expected Behavior
Webpack should build.

## Actual Behavior
Webpack prematurely finishes building, pages not served.

## Steps to Reproduce

1. Checkout latest branch
2. npm serve
3.
4.

## Your Environment

* Mac Sierra
* Chrome

**Comment by romoy** [comment]
Fixed by https://github.com/codefordc/dc-campaign-finance-watch/pull/222
