### ISSUE TITLE
Homepage (https://codefordc.org/dc-campaign-finance-watch/) is just a blank page

### ISSUE THREAD

**Issue by NoahCarnahan** [codefordc/dc-campaign-finance-watch#228]
## Context
I just discovered this project, and went to check it out by clicking the link in the repo description, which links to https://codefordc.org/dc-campaign-finance-watch/. That page redirects me to https://codefordc.org/dc-campaign-finance-watch/dist/, which is just a blank page (with top bar navigation).

## Expected Behavior
I expect a page with some content, like the list of candidates that I get if I click the "Home" tab.

**Comment by NoahCarnahan** [comment]
I took a shot at this here: https://github.com/codefordc/dc-campaign-finance-watch/pull/229

**Comment by mkalish** [comment]
Closed by #229
