### ISSUE TITLE
Certificate Expired on https://campaign-finance.codefordc.org/

### ISSUE THREAD

**Issue by tacman** [codefordc/dc-campaign-finance-watch#230]
## Actual Behavior

Warning message about site not being secure

![image](https://user-images.githubusercontent.com/619585/38835365-50c2cb48-4199-11e8-9c8f-55fa3cd46c39.png)

## Possible Fix

Renew the certificate (LetsEncrypt?)

**Comment by mkalish** [comment]
@tacman Thanks for the issue, totally slipped my mind to renew it.  It'll be back up when I get home from work.

**Comment by tacman** [comment]
Thanks, Michael.  I'd like to get involved with this project, at least get
the data current for this cycle.

Will you be at the meetup tonight?
https://www.meetup.com/Code-for-DC/events/248658894/

Tac

**Comment by mkalish** [comment]
@tacman Unfortunately, I won't make it to the meetup tonight, got stuck at work late.  But I'm always looking for folks to get involved.  I actually just finished scraping the current cycles date (well through april 1st) here http://data.codefordc.org/dataset/dc-campaign-contributions (look at in firefox)

I'm currently in the process of beginning to convert the existing API to pull data from the updated sources.

We have a channel in the code for dc slack if you have any things you want to work on.

**Comment by tacman** [comment]
Thanks, I'll poke around.  Ran into this.

http://data.codefordc.org/dataset/dc-campaign-contributions/resource/b1932cfe-1cf4-4f87-9ba8-9c65121ea6c4

**Comment by mkalish** [comment]
Cert has been renewed
