### ISSUE TITLE
Slow Lookup & Visualization

### ISSUE THREAD

**Issue by donaldbraman** [codefordc/dc-campaign-finance-watch#57]
I wonder if there is a way to speed things up a bit.  

First, as a stopgap, maybe add a preloading graphic so people will know that it is loading.  Maybe also time common  queries and give folks a heads up on the typical amount of time they should wait so they know whether to  hang in there waiting or close the browser and try again.  

Then, if it makes sense, maybe cache the names of candidates.  Maybe keep the top 100 queries (in json or whatever) on github each night so they can load quickly.  Assuming people search for similar things, only novel searches will take a long time.

**Comment by mkalish** [comment]
Completely agree.  At the bare minimum a loading spinner is going to be required.  I'm definitely looking into trying to speed up the loading, but I think I'll split that into a second issue.
