### ISSUE TITLE
Update README to reflect new vagrant setup

### ISSUE THREAD

**Issue by mkalish** [codefordc/dc-campaign-finance-watch#61]
The README should be updated to reflect the new setup with vagrant

**Comment by romoy** [comment]
updating

**Comment by romoy** [comment]
updated

**Comment by mkalish** [comment]
Is there a Pull request for this?

**Comment by romoy** [comment]
https://github.com/codefordc/dc-campaign-finance-watch/pull/62 
it's merged;
