### ISSUE TITLE
update master to be develop

### ISSUE THREAD

**Issue by romoy** [codefordc/dc-campaign-finance-watch#63]
Update master to be at the same level as develop for "develop" sake;
Whenever someone clone the repo, it's confusing that master is not the latest, and require extra effort explaining which branch to use

**Comment by romoy** [comment]
Is this following https://www.atlassian.com/git/tutorials/setting-up-a-repository?

**Comment by mkalish** [comment]
We can go ahead and do this, but I've also updated the repo to use develop as the default branch moving forward

**Comment by romoy** [comment]
ah, if develop is the default; this isn't needed
