### ISSUE TITLE
We need explanations for the candidates score cards

### ISSUE THREAD

**Issue by mkalish** [codefordc/dc-campaign-finance-watch#69]
65% from within DC: -10
85% of contributions were for the maximum: -5

85% of records completed to the legal limit: -5
15% of records were compliant: -5

**Comment by jkoul** [comment]
@mkalish we'll need to actually create the scorecard parameters before writing the explanation. But I'll interpret this issue as a general "scorecard stuff" placeholder.

**Comment by jkoul** [comment]
We actually still need this explanation for the scorecard, but I'll create a new issue since it looks like I can't reopen this one. It can look a lot like the README I put together.....and for now maybe the readme itself would suffice?

**Comment by mkalish** [comment]
I think a README is 100% okay.  And rather than linking, I can't actually just take the markdown and display it in the site.

I'll keep this one closed though since you opened a new one
